import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

import { ThemeProvider } from '@/components/theme-provider'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: [
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900'
  ],
})

export const metadata: Metadata = {
  title: 'Courts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang="pt-br" suppressHydrationWarning>
        <body
          className={`${poppins.variable} antialiased pb-20`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
